# Generated by Django 3.1.14 on 2024-03-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20240306_2225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicantRegistration',
            new_name='Applicant_Registration',
        ),
    ]
