# Generated by Django 3.1.14 on 2024-03-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_auto_20240306_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant_registration',
            options={'verbose_name_plural': 'Candidate Application'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name_plural': 'JAMB Result Upload'},
        ),
        migrations.AddField(
            model_name='applicant_registration',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='applicant_registration',
            name='phone',
            field=models.CharField(default='234', max_length=25),
        ),
        migrations.AddField(
            model_name='applicant_registration',
            name='reg_No',
            field=models.CharField(default='23u764', max_length=20),
        ),
    ]
