# Generated by Django 3.1.14 on 2024-03-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_auto_20240309_1919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locality',
        ),
    ]
