# Generated by Django 3.1.14 on 2024-03-17 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_delete_locality'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='applicant_registration',
            name='lga_Origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admission.lga'),
            preserve_default=False,
        ),
    ]
