# Generated by Django 3.1.14 on 2024-03-17 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_auto_20240317_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='applicant_registration',
            name='choice_One',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='admission.choiceone', unique=True),
        ),
        migrations.AddField(
            model_name='applicant_registration',
            name='choice_Three',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='admission.choicethree', unique=True),
        ),
        migrations.AddField(
            model_name='applicant_registration',
            name='choice_Two',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='admission.choicetwo', unique=True),
        ),
    ]
