# Generated by Django 3.2.24 on 2024-03-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_auto_20240317_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_registration',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
