# Generated by Django 3.2.24 on 2024-03-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_applicant_registration_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant_registration',
            name='name',
        ),
        migrations.AddField(
            model_name='applicant_registration',
            name='first_Name',
            field=models.CharField(default='select', max_length=150),
        ),
        migrations.AddField(
            model_name='applicant_registration',
            name='other_Name',
            field=models.CharField(default='select', max_length=150),
        ),
        migrations.AddField(
            model_name='applicant_registration',
            name='surname',
            field=models.CharField(default='select', max_length=150),
        ),
    ]
