# Generated by Django 3.2.24 on 2024-04-08 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0011_department_nationality_student_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('course_Code', models.CharField(max_length=10)),
                ('credit_units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('has_paid_acceptance_fee', models.BooleanField(default=False)),
                ('has_paid_school_fees', models.BooleanField(default=False)),
                ('credit_units_limit', models.IntegerField(default=0)),
                ('probation_years', models.IntegerField(default=0)),
                ('grade_points', models.FloatField(default=0.0)),
                ('matrix_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.grade')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.studentacceptance')),
            ],
        ),
    ]
