# Generated by Django 3.2.24 on 2024-04-09 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_auto_20240409_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 17, 48, 25, 745256)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 17, 48, 25, 745256)),
        ),
    ]
