# Generated by Django 3.2.24 on 2024-04-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultprocessing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_score', models.IntegerField()),
                ('grade_letter', models.CharField(max_length=1)),
                ('gp', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='is_carry_over',
            field=models.BooleanField(default=False),
        ),
    ]
